/opt/raku/logs/rakuxq/access.log /opt/raku/logs/rakuxq/error.log {
    hourly
    rotate 48
    missingok
    notifempty
    compress
    delaycompress
    copytruncate
    dateext
    dateformat -%Y%m%d-%H
    su root root
}
